# -*- coding: utf-8 -*-
"""Multivariate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggD3c6HWOWd5iYm66X3xPCy8mIfr3GuW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.datasets import make_regression

x, y = make_regression(
    n_samples=100,
    n_features=3,
    noise=10,
    random_state=42
)

df = pd.DataFrame(x, columns=['x1', 'x2', 'x3'])
df['y'] = y
df.head()

x = df[['x1','x2','x3']]
y=df['y']
model = LinearRegression()
model.fit(x,y)
df['predicted'] = model.predict(x)

r2 =r2_score(y, df['predicted'])

n = x.shape[0]
p = x.shape[1]
adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)

plt.scatter(range(len(y)), df['y'], color='blue', label='Actual')
plt.scatter(range(len(y)), df['predicted'], color='red', label='Predicted values')
plt.xlabel('Data Points')
plt.ylabel('Target values')
plt.title('Actual vs Predicted Values')
plt.legend()
plt.show()

print("R-squard:", r2)
print("Adjusted R-squared:", adj_r2)