# -*- coding: utf-8 -*-
"""Nadaraya_watson Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zsN_uArOujg0_eSXR1TnSt6dFthIqSem
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([1, 2, 3, 4, 5])
y = np.array([1.2, 1.9, 3.0, 3.9, 5.1])
x_test = np.linspace(1, 5, 100)

def gaussian_kernal(x1, x2, bandwidth):
  return np.exp(-0.5*((x1-x2)/bandwidth) ** 2)

def nadaraya_watson(X, y, x_test, bandwidth):
  y_pred = []

  for x in x_test:
    weights = gaussian_kernal(x, X, bandwidth)
    y_hat = np.sum(weights * y) / np.sum(weights)
    y_pred.append(y_hat)

  return np.array(y_pred)

x_test = np.linspace(1, 5, 100)
bandwidth = 0.01
y_pred = nadaraya_watson(x, y, x_test, bandwidth)

plt.scatter(x, y,color='red', label='Data Points')
plt.plot(x_test, y_pred, label='Nadaraya-watson Regression')
plt.xlabel('x')
plt.ylabel('y')
plt.title('NON-parametric Nadaraya-watson Regression')
plt.legend()
plt.grid()
plt.show()