# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlXM4wGTYcoxzvueqCCIEhOS5dbO1Nm6
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

np.random.seed(0)
heights = np.random.normal(165, 10, 100)
weights = 0.5 * heights - 30 + np.random.normal(0, 5, 100)
x = np.column_stack((heights, weights))
plt.scatter(x[:,0], x[:,1], alpha=0.7)
plt.xlabel("Height (cm)")
plt.ylabel("Weight (kg)")
plt.title("Original Dataset (100 studenyts)")
plt.grid()
plt.show()

scalar = StandardScaler()
x_scaled = scalar.fit_transform(x)

plt.scatter(x_scaled[:,0], x_scaled[:,1], alpha = 0.7, color = 'green')
plt.xlabel("Height (scaled)")
plt.ylabel("Weight (scaled)")
plt.title("Standardized (scaled Data)")
plt.grid()
plt.show()

pca_1d = PCA(n_components=1)
x_1d = pca_1d.fit_transform(x_scaled)
print("Explained Variance:")
print(pca_1d.explained_variance_)
print("Frist 10 values of 1D PCA output:")
print(x_1d[:10])