# -*- coding: utf-8 -*-
"""Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGeMlD2aNVt7--NunS7AZEllo7eh-jlW
"""

import numpy as np
oneD_array = np.array([1, 3, 4,5 ])
type(oneD_array)
print(oneD_array)

twoD_array = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5] # Changed to have 4 elements to match the first row
])

#UFuncs (Universal function)

numbers = [1, 1, 2, 3, 3, 4, 6]

max(numbers)

np.mean(numbers)

min(numbers)

#Slicing

data = [10, 20, 30, 40, 50, 60, 70, 80]
data[3:7]

fruits = np.array(['apple', 'banana', 'coconut'])

fruits

np.array(['apple', 'banana', 'coconut'])

import numpy as np
df = np.arange(6) # Example: creating a 1D array with 6 elements
data = df.reshape(2, 3) # Reshaping it into a 2x3 2D array

list = [1, 2, 3 ,4]

list[1]

#boolean indexing and broadcasting

data

df = data.ravel()
df

filter = df > 3
filter

df[filter]

fruits = np.append(fruits, 'grape')
fruits

filter_fruits = fruits == 'apple'
filter_fruits

#Broadcasting

oneD_array = np.array([1, 2, 3, 4, 5])
oneD_array

twoD_array = np.array([
    [1, 2, 3, 4, 55, 5, 6 ],
    [2, 3, 5, 6, 66, 7, 77,]
])
twoD_array
twoD_array.shape

oneD_array_compatible = np.array([1, 2, 3, 4, 5, 0, 0])

# Perform the addition with the compatible array
sum_result = oneD_array_compatible + twoD_array
print(sum_result)